// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimplyShopAPI.Infrastructure.Context;

#nullable disable

namespace SimplyShopAPI.Infrastructure.Migrations.App
{
    [DbContext(typeof(SimplyShopContext))]
    partial class SimplyShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand_name");

                    b.Property<string>("BrandNameDisplay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand_name_display");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("BrandId");

                    b.HasIndex(new[] { "BrandName" }, "unique_brand_names")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemNameDisplay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("item_name_display");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ItemId");

                    b.HasIndex(new[] { "ItemName" }, "unique_item_names")
                        .IsUnique();

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.PackageDefinition", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("PackageDescr")
                        .HasColumnType("text")
                        .HasColumnName("package_description");

                    b.Property<decimal>("PackageSize")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("package_size");

                    b.Property<int>("UnitTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type_id");

                    b.HasKey("ProductId");

                    b.HasIndex("UnitTypeId");

                    b.ToTable("package_definitions", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("UnitTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_type_id");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("UnitTypeId");

                    b.HasIndex(new[] { "ItemId", "BrandId", "UnitTypeId" }, "unique_products")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreId"));

                    b.Property<string>("CityAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city_address");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry (point, 4326)")
                        .HasColumnName("location");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("StateAddress")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_address");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("store_name");

                    b.Property<string>("StoreNameDisplay")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("store_name_display");

                    b.Property<int>("StoreStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("store_status_id");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("street_address");

                    b.Property<string>("ZipAddress")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("zip_address");

                    b.HasKey("StoreId");

                    b.HasIndex("StoreStatusId");

                    b.HasIndex(new[] { "StoreName", "StreetAddress", "ZipAddress" }, "unique_stores")
                        .IsUnique();

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.StoreStatus", b =>
                {
                    b.Property<int>("StoreStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("store_status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreStatusId"));

                    b.Property<string>("StoreStatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_status_name");

                    b.HasKey("StoreStatusId");

                    b.HasIndex(new[] { "StoreStatusName" }, "unique_store_statuses")
                        .IsUnique();

                    b.ToTable("store_statuses", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("StoreId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.UnitType", b =>
                {
                    b.Property<int>("UnitTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitTypeId"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UnitTypeAbbrev")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("unit_type_abbrev");

                    b.Property<string>("UnitTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_type_name");

                    b.HasKey("UnitTypeId");

                    b.HasIndex(new[] { "UnitTypeName" }, "unique_unit_types")
                        .IsUnique();

                    b.ToTable("unit_types", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("last_name");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("zip_code");

                    b.HasKey("ProfileId");

                    b.HasIndex(new[] { "IdentityUserId" }, "unique_identity_user_id")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.PackageDefinition", b =>
                {
                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.Product", "Product")
                        .WithOne("PackageDefinition")
                        .HasForeignKey("SimplyShopAPI.Infrastructure.Entities.PackageDefinition", "ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("package_definitions_product_id_fkey");

                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.UnitType", "UnitType")
                        .WithMany("PackageDefinitions")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("package_definitions_unit_type_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Product", b =>
                {
                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("products_brand_id_fkey");

                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.Item", "Item")
                        .WithMany("Products")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("products_item_id_fkey");

                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.UnitType", "UnitType")
                        .WithMany("Products")
                        .HasForeignKey("UnitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("products_unit_type_id_fkey");

                    b.Navigation("Brand");

                    b.Navigation("Item");

                    b.Navigation("UnitType");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Store", b =>
                {
                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.StoreStatus", "StoreStatus")
                        .WithMany("Stores")
                        .HasForeignKey("StoreStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("stores_store_status_id_fkey");

                    b.Navigation("StoreStatus");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Transaction", b =>
                {
                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.Product", "Product")
                        .WithMany("Transactions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transactions_product_id_fkey");

                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.UserProfile", "UserProfile")
                        .WithMany("Transactions")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("transactions_user_profile_id_fkey");

                    b.HasOne("SimplyShopAPI.Infrastructure.Entities.Store", "Store")
                        .WithMany("Transactions")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("transactions_store_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("Store");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Item", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Product", b =>
                {
                    b.Navigation("PackageDefinition");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.Store", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.StoreStatus", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.UnitType", b =>
                {
                    b.Navigation("PackageDefinitions");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SimplyShopAPI.Infrastructure.Entities.UserProfile", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
