CREATE EXTENSION IF NOT EXISTS postgis;
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_SimplyShop" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_SimplyShop" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE brands (
    brand_id integer GENERATED BY DEFAULT AS IDENTITY,
    brand_name character varying(50) NOT NULL,
    brand_name_display character varying(50) NOT NULL,
    date_created timestamp with time zone NOT NULL DEFAULT (now()),
    last_updated timestamp with time zone DEFAULT (now()),
    CONSTRAINT "PK_brands" PRIMARY KEY (brand_id)
);

CREATE TABLE items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY,
    item_name character varying(50) NOT NULL,
    item_name_display character varying(50) NOT NULL,
    date_created timestamp with time zone NOT NULL DEFAULT (now()),
    last_updated timestamp with time zone DEFAULT (now()),
    CONSTRAINT "PK_items" PRIMARY KEY (item_id)
);

CREATE TABLE store_statuses (
    store_status_id integer GENERATED BY DEFAULT AS IDENTITY,
    store_status_name text NOT NULL,
    CONSTRAINT "PK_store_statuses" PRIMARY KEY (store_status_id)
);

CREATE TABLE unit_types (
    unit_type_id integer GENERATED BY DEFAULT AS IDENTITY,
    unit_type_name character varying(50) NOT NULL,
    unit_type_abbrev character varying(25),
    date_created timestamp with time zone NOT NULL DEFAULT (now()),
    last_updated timestamp with time zone DEFAULT (now()),
    CONSTRAINT "PK_unit_types" PRIMARY KEY (unit_type_id)
);

CREATE TABLE user_profiles (
    profile_id integer GENERATED BY DEFAULT AS IDENTITY,
    identity_user_id text NOT NULL,
    first_name character varying(25) NOT NULL,
    last_name character varying(25) NOT NULL,
    zip_code character varying(6),
    CONSTRAINT "PK_user_profiles" PRIMARY KEY (profile_id)
);

CREATE TABLE stores (
    store_id integer GENERATED BY DEFAULT AS IDENTITY,
    store_name character varying(30) NOT NULL,
    store_name_display character varying(30) NOT NULL,
    street_address character varying(50) NOT NULL,
    city_address character varying(50) NOT NULL,
    state_address character varying(2) NOT NULL,
    zip_address character varying(6) NOT NULL,
    latitude double precision,
    longitude double precision,
    location geometry (point, 4326),
    date_created timestamp with time zone NOT NULL DEFAULT (now()),
    last_updated timestamp with time zone DEFAULT (now()),
    store_status_id integer NOT NULL,
    CONSTRAINT "PK_stores" PRIMARY KEY (store_id),
    CONSTRAINT stores_store_status_id_fkey FOREIGN KEY (store_status_id) REFERENCES store_statuses (store_status_id) ON DELETE RESTRICT
);

CREATE TABLE products (
    product_id integer GENERATED BY DEFAULT AS IDENTITY,
    item_id integer NOT NULL,
    unit_type_id integer,
    brand_id integer,
    date_created timestamp with time zone NOT NULL DEFAULT (now()),
    last_updated timestamp with time zone DEFAULT (now()),
    CONSTRAINT "PK_products" PRIMARY KEY (product_id),
    CONSTRAINT products_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES brands (brand_id) ON DELETE SET NULL,
    CONSTRAINT products_item_id_fkey FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE RESTRICT,
    CONSTRAINT products_unit_type_id_fkey FOREIGN KEY (unit_type_id) REFERENCES unit_types (unit_type_id) ON DELETE RESTRICT
);

CREATE TABLE package_definitions (
    product_id integer NOT NULL,
    unit_type_id integer NOT NULL,
    package_description text,
    package_size numeric(12,2) NOT NULL,
    CONSTRAINT "PK_package_definitions" PRIMARY KEY (product_id),
    CONSTRAINT package_definitions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE RESTRICT,
    CONSTRAINT package_definitions_unit_type_id_fkey FOREIGN KEY (unit_type_id) REFERENCES unit_types (unit_type_id) ON DELETE RESTRICT
);

CREATE TABLE transactions (
    transaction_id integer GENERATED BY DEFAULT AS IDENTITY,
    quantity numeric NOT NULL,
    cost numeric(12,2) NOT NULL,
    transaction_date timestamp with time zone NOT NULL DEFAULT (now()),
    profile_id integer,
    store_id integer NOT NULL,
    product_id integer NOT NULL,
    CONSTRAINT "PK_transactions" PRIMARY KEY (transaction_id),
    CONSTRAINT transactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE CASCADE,
    CONSTRAINT transactions_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores (store_id) ON DELETE CASCADE,
    CONSTRAINT transactions_user_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES user_profiles (profile_id)
);

CREATE UNIQUE INDEX unique_brand_names ON brands (brand_name);

CREATE UNIQUE INDEX unique_item_names ON items (item_name);

CREATE INDEX "IX_package_definitions_unit_type_id" ON package_definitions (unit_type_id);

CREATE INDEX "IX_products_brand_id" ON products (brand_id);

CREATE INDEX "IX_products_unit_type_id" ON products (unit_type_id);

CREATE UNIQUE INDEX unique_products ON products (item_id, brand_id, unit_type_id);

CREATE UNIQUE INDEX unique_store_statuses ON store_statuses (store_status_name);

CREATE INDEX "IX_stores_store_status_id" ON stores (store_status_id);

CREATE UNIQUE INDEX unique_stores ON stores (store_name, street_address, zip_address);

CREATE INDEX "IX_transactions_product_id" ON transactions (product_id);

CREATE INDEX "IX_transactions_profile_id" ON transactions (profile_id);

CREATE INDEX "IX_transactions_store_id" ON transactions (store_id);

CREATE UNIQUE INDEX unique_unit_types ON unit_types (unit_type_name);

CREATE UNIQUE INDEX unique_identity_user_id ON user_profiles (identity_user_id);

INSERT INTO "__EFMigrationsHistory_SimplyShop" ("MigrationId", "ProductVersion")
VALUES ('20260113034730_AppInit', '8.0.22');

COMMIT;

