CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory_Identity" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory_Identity" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE roles (
    role_id text NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_roles" PRIMARY KEY (role_id)
);

CREATE TABLE users (
    user_id text NOT NULL,
    date_created timestamp with time zone NOT NULL DEFAULT (now()),
    last_updated timestamp with time zone DEFAULT (now()),
    username character varying(256),
    normalized_username character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY (user_id)
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES roles (role_id) ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    refresh_token_id uuid NOT NULL,
    user_id text NOT NULL,
    token_hash text NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    expires_at_utc timestamp with time zone NOT NULL,
    "RevokedAtUtc" timestamp with time zone,
    "ReplacedByTokenHash" text,
    CONSTRAINT "PK_refresh_tokens" PRIMARY KEY (refresh_token_id),
    CONSTRAINT "FK_refresh_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE user_claims (
    user_claim_id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_user_claims" PRIMARY KEY (user_claim_id),
    CONSTRAINT "FK_user_claims_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id text NOT NULL,
    CONSTRAINT "PK_user_logins" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_user_logins_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT "PK_user_roles" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_user_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE CASCADE,
    CONSTRAINT "FK_user_roles_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE user_tokens (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_user_tokens" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_user_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "IX_refresh_tokens_token_hash" ON refresh_tokens (token_hash);

CREATE INDEX "IX_refresh_tokens_user_id" ON refresh_tokens (user_id);

CREATE UNIQUE INDEX "RoleNameIndex" ON roles (normalized_name);

CREATE INDEX "IX_user_claims_user_id" ON user_claims (user_id);

CREATE INDEX "IX_user_logins_user_id" ON user_logins (user_id);

CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);

CREATE INDEX "EmailIndex" ON users (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON users (normalized_username);

INSERT INTO "__EFMigrationsHistory_Identity" ("MigrationId", "ProductVersion")
VALUES ('20260113034743_IdentityInit', '8.0.22');

COMMIT;

